"""empty message

Revision ID: 443e34a2cdd8
Revises: 
Create Date: 2017-02-18 16:29:43.011798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '443e34a2cdd8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=36), nullable=False),
    sa.Column('permissoes', sa.Integer(), nullable=False),
    sa.Column('padrao', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permissoes')
    )
    op.create_index(op.f('ix_cargos_nome'), 'cargos', ['nome'], unique=True)
    op.create_index(op.f('ix_cargos_padrao'), 'cargos', ['padrao'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=64), nullable=False),
    sa.Column('senha_hash', sa.String(length=128), nullable=True),
    sa.Column('confirmado', sa.Boolean(), nullable=True),
    sa.Column('id_cargo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cargo'], ['cargos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_email'), 'usuarios', ['email'], unique=True)
    op.create_index(op.f('ix_usuarios_nome'), 'usuarios', ['nome'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint(u'(srid > 0) AND (srid <= 998999)', name=u'spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name=u'spatial_ref_sys_pkey')
    )
    op.drop_index(op.f('ix_usuarios_nome'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_email'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_cargos_padrao'), table_name='cargos')
    op.drop_index(op.f('ix_cargos_nome'), table_name='cargos')
    op.drop_table('cargos')
    # ### end Alembic commands ###
