"""empty message

Revision ID: 7937aa0a1ba7
Revises: 41411ce7eda3
Create Date: 2017-02-22 09:30:02.418038

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7937aa0a1ba7'
down_revision = '41411ce7eda3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ambientes', sa.Column('id_bloco', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ambientes', 'blocos', ['id_bloco'], ['id'])
    op.drop_constraint(u'ambientes_externos_id_bloco_fkey', 'ambientes_externos', type_='foreignkey')
    op.drop_column('ambientes_externos', 'id_bloco')
    op.drop_constraint(u'ambientes_internos_id_bloco_fkey', 'ambientes_internos', type_='foreignkey')
    op.drop_column('ambientes_internos', 'id_bloco')
    op.drop_index('idx_blocos_localizacao', table_name='blocos')
    op.drop_index('idx_campi_mapeamento', table_name='campi')
    op.drop_index('idx_centros_mapeamento', table_name='centros')
    op.drop_index('idx_subestacoes_abrigadas_localizacao', table_name='subestacoes_abrigadas')
    op.drop_constraint(u'subestacoes_abrigadas_id_campus_fkey', 'subestacoes_abrigadas', type_='foreignkey')
    op.drop_column('subestacoes_abrigadas', 'id_campus')
    op.drop_index('idx_subestacoes_aereas_localizacao', table_name='subestacoes_aereas')
    op.drop_constraint(u'subestacoes_aereas_id_campus_fkey', 'subestacoes_aereas', type_='foreignkey')
    op.drop_column('subestacoes_aereas', 'id_campus')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subestacoes_aereas', sa.Column('id_campus', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'subestacoes_aereas_id_campus_fkey', 'subestacoes_aereas', 'campi', ['id_campus'], ['id'])
    op.create_index('idx_subestacoes_aereas_localizacao', 'subestacoes_aereas', ['localizacao'], unique=False)
    op.add_column('subestacoes_abrigadas', sa.Column('id_campus', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'subestacoes_abrigadas_id_campus_fkey', 'subestacoes_abrigadas', 'campi', ['id_campus'], ['id'])
    op.create_index('idx_subestacoes_abrigadas_localizacao', 'subestacoes_abrigadas', ['localizacao'], unique=False)
    op.create_index('idx_centros_mapeamento', 'centros', ['mapeamento'], unique=False)
    op.create_index('idx_campi_mapeamento', 'campi', ['mapeamento'], unique=False)
    op.create_index('idx_blocos_localizacao', 'blocos', ['localizacao'], unique=False)
    op.add_column('ambientes_internos', sa.Column('id_bloco', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'ambientes_internos_id_bloco_fkey', 'ambientes_internos', 'blocos', ['id_bloco'], ['id'])
    op.add_column('ambientes_externos', sa.Column('id_bloco', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(u'ambientes_externos_id_bloco_fkey', 'ambientes_externos', 'blocos', ['id_bloco'], ['id'])
    op.drop_constraint(None, 'ambientes', type_='foreignkey')
    op.drop_column('ambientes', 'id_bloco')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint(u'(srid > 0) AND (srid <= 998999)', name=u'spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name=u'spatial_ref_sys_pkey')
    )
    # ### end Alembic commands ###
